### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by capriciousduck** [trulyshelton/GoogleDriveProxy#6]
Hi, I previously used your "[GoogleDriveDownloader](https://github.com/capriciousduck/g-uploader)" app. And I am still using it. Since I found that you no longer have that app in your repositories I wanted to contact you for some help. But I didn't find a way to contact you. So I am using an issue to contact you.

Regarding the app, the app is working fine. But after long periods of inactivity, when I add new links to the app the status of the download bar doesn't change, and also the file is not downloding. When I checked the logs I see that "GET API ...some error code" keeps on printing in the console. I request you to help me.

Thanks,
capriciousduck

**Comment by trulyshelton** [comment]
That repo is deleted because it is not reliable and I am no longer maintaining it
